### ISSUE TITLE
broadcast error message

### ISSUE THREAD

**Issue by brandonm78** [synlestidae/ethereum-tx-sign#62] opened 2022-09-10 22:34 UTC
I started using ethereum-tx-sign which is great by the way.  Today, I experienced an error when broadcasting the signed transaction.  

It said: 
 Error -32000, rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.LegacyTx).R

I did not capture the signed transaction has to provide but I did look up the error and found the following.

    https://github.com/MOACChain/moac-core/issues/24

I wanted the mention this in case its also an issue here.

**Comment by brandonm78** [comment] 2022-09-10 23:48
I am able to repeat the issue fairly easily.  I ran 100000 signs and it happened 387 times.  

I confirmed the it's as the thread says.  Leading 0 padding on the R value when it should be stripped.  I am not sure if its also affecting the other values and if there is padding there that needs stripping as well.  I just looked at the R value.

Let me know if you need an example transaction.

**Comment by synlestidae** [comment] 2022-09-18 23:53
Thank you, and sorry I didn’t see your issue immediately. I consider any
signing a serious bug so I would like to get on to it as soon as I can.

Please could you supply me some of your examples? If you feel up to it, you
could add it to the test/
<https://github.com/synlestidae/ethereum-tx-sign/tree/master/test>
directory, write a unit test(s) in lib.rs, and create a
pull request to development. This would help me greatly. In any case I need
to recreate the problem.

Cheddar!

**Comment by gioelecerati** [comment] 2022-09-19 00:11
Looks like the same problem that was fixed in #13, doesn't look like that part of the code was brought in when updating the signing function

**Comment by synlestidae** [comment] 2022-09-19 00:35
Great spotting @gioelecerati. I'll add that fix in first thing

**Comment by synlestidae** [comment] 2022-09-19 07:20
I pushed a fix to _development_ @brandonm78:  80b7de8774524f8b

Would you like to try this out? Add it as a [Git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) using the `rev` or `branch` syntax.

**Comment by brandonm78** [comment] 2022-09-19 08:16
It's now working for me.

Here is the results of a test:

Raw Transaction: (with the fix): f9016b82098a843b9aca008303d0c2947d0556d55ca1a92708681e2e231733ebd922597d80b9010438ed17390000000000000000000000000000000000000000000000001bc16d674ec800000000000000000000000000000000000000000000000000000000000099faf20800000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000d53000053e91597add02e491536628c40c9072d8000000000000000000000000000000000000000000000000000000006328052c0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c99a6a985ed2cac1ef41640596c5a5f9f4e19ef50000000000000000000000000b7007c13325c48911f73a2dad5fa5dcbf808adc259f49cbe6909c004f0d0696ce4ae2aa43d092bc42a2609749a68ff4275dec64b3a02de2cbb3efece0ece13d36bb0a8310ca05014ae06e8e5ded2e60ba7449777fa7

Raw Transaction (without the fix): f9016c82098a843b9aca008303d0c2947d0556d55ca1a92708681e2e231733ebd922597d80b9010438ed17390000000000000000000000000000000000000000000000001bc16d674ec800000000000000000000000000000000000000000000000000000000000099faf20800000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000d53000053e91597add02e491536628c40c9072d8000000000000000000000000000000000000000000000000000000006328052c0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c99a6a985ed2cac1ef41640596c5a5f9f4e19ef50000000000000000000000000b7007c13325c48911f73a2dad5fa5dcbf808adc25a00049cbe6909c004f0d0696ce4ae2aa43d092bc42a2609749a68ff4275dec64b3a02de2cbb3efece0ece13d36bb0a8310ca05014ae06e8e5ded2e60ba7449777fa7

And the fake test transaction that resulted in the error:

data: 0x38ed17390000000000000000000000000000000000000000000000001bc16d674ec800000000000000000000000000000000000000000000000000000000000099faf20800000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000d53000053e91597add02e491536628c40c9072d8000000000000000000000000000000000000000000000000000000006328052c0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c99a6a985ed2cac1ef41640596c5a5f9f4e19ef50000000000000000000000000b7007c13325c48911f73a2dad5fa5dcbf808adc
gasPrice: 1000000000
nonce: 2442
to: 0x7D0556D55ca1a92708681e2e231733EBd922597D
chain: 1
value: 0
gas: 250050
Private Key: 0x49c481074964b22585b4fb3e662e6ce8f75a22b50267419a8182a4efd1f602a9

Hope that helps
Brandon

**Comment by synlestidae** [comment] 2022-09-20 07:59
Glad to hear. I've added your data to the test suite, thank you. Could not reproduce the test failure on an older commit. But I'll consider this resolved now.

**Closed by synlestidae** 2022-09-20 07:59 UTC
